"""Export the reportable devices (elevators and escalators) for the outage-report back end.

The station graphs split an elevator into one edge per hop (step in, ride, step out), so a
broken elevator must block every edge of its shaft. A device is therefore a connected group of
elevator edges, or a single escalator edge. The back end only accepts reports on these edges and
expands a report on one edge to its whole device (supabase/migrations, `report_outage`).

Output: data/build/supabase/devices.sql, loaded by `supabase db reset` (supabase/config.toml).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from importer.graph.export import BUILD_DIR

SUPABASE_DIR = BUILD_DIR.parent / "supabase"
REPORTABLE = ("elevator", "escalator")


def device_rows(graph: dict) -> list[dict[str, Any]]:
    """One row per reportable edge, with the id of the device it belongs to."""
    station_id = graph["station"]["id"]
    nodes = {n["id"]: n for n in graph["nodes"]}
    elevators = [e for e in graph["edges"] if e["mode"] == "elevator"]

    # Union-find over the nodes the elevator edges touch.
    parent: dict[str, str] = {}

    def find(x: str) -> str:
        parent.setdefault(x, x)
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for e in elevators:
        parent[find(e["from"])] = find(e["to"])
    shafts: dict[str, list[dict]] = {}
    for e in elevators:
        shafts.setdefault(find(e["from"]), []).append(e)

    groups: list[tuple[str, list[dict]]] = [("elevator", es) for es in shafts.values()]
    groups += [("escalator", [e]) for e in graph["edges"] if e["mode"] == "escalator"]

    rows: list[dict[str, Any]] = []
    for mode, edges in groups:
        device_id = f"{station_id}:{mode}:{min(e['id'] for e in edges).split(':')[-1]}"
        ends = [nodes[n] for e in edges for n in (e["from"], e["to"])]
        lon = sum(n["lon"] for n in ends) / len(ends)
        lat = sum(n["lat"] for n in ends) / len(ends)
        for e in edges:
            rows.append({
                "edge_id": e["id"],
                "device_id": device_id,
                "station_id": station_id,
                "pathway_id": e.get("pathwayId"),
                "mode": mode,
                "lon": round(lon, 7),
                "lat": round(lat, 7),
            })
    return sorted(rows, key=lambda r: r["edge_id"])


def _lit(value: str | None) -> str:
    return "null" if value is None else "'" + value.replace("'", "''") + "'"


def devices_sql(graphs: list[dict]) -> str:
    """An idempotent upsert of the devices of these stations; devices that vanished are removed."""
    rows = [r for g in graphs for r in device_rows(g)]
    station_ids = ", ".join(_lit(g["station"]["id"]) for g in graphs)
    edge_ids = ", ".join(_lit(r["edge_id"]) for r in rows)
    values = ",\n".join(
        f"  ({_lit(r['edge_id'])}, {_lit(r['device_id'])}, {_lit(r['station_id'])}, "
        f"{_lit(r['pathway_id'])}, {_lit(r['mode'])}, "
        f"extensions.st_setsrid(extensions.st_makepoint({r['lon']}, {r['lat']}), 4326))"
        for r in rows
    )
    return (
        "-- Generated by importer.graph.devices (uv run python -m importer.run). Do not edit.\n"
        "begin;\n"
        f"delete from public.station_devices where station_id in ({station_ids})"
        f" and edge_id not in ({edge_ids});\n"
        "insert into public.station_devices"
        " (edge_id, device_id, station_id, pathway_id, mode, geom) values\n"
        f"{values}\n"
        "on conflict (edge_id) do update set device_id = excluded.device_id,"
        " station_id = excluded.station_id, pathway_id = excluded.pathway_id,"
        " mode = excluded.mode, geom = excluded.geom;\n"
        "commit;\n"
    )


def export_devices(graphs: list[dict], out_dir: Path = SUPABASE_DIR) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "devices.sql"
    path.write_text(devices_sql(graphs), encoding="utf-8")
    return path
